% CUEBMS_CLUSTERMERGEMAKE compiles CueBMS_clusterMerge

mcc -o CueBMS_clustermerge ...
    -W WinMain:CueBMS_clustermerge ...
    -T link:exe ...
    -R -singleCompThread -R -nojvm ...
    -w enable:specified_file_mismatch -w enable:repeated_file -w enable:switch_ignored -w enable:missing_lib_sentinel -w enable:demo_license ...
    -v ModelWork_clusterMerge.m ...
    -a ModelBag_add.m -a ModelBag_get.m -a ModelBag_index.m -a ModelWork_batchmerge.m -a ModelWork_compare.m -a ModelWork_getmodelstring.m ...
    -a ModelWork_modelFit.m -a ModelWork_plotChains.m ...
    -a CueBMS_batchrunInit.m -a CueBMS_modelFitBits.m -a CueBMS_setupModel.m ...
    -a CueBMS_datalike.m -a CueBMS_UnimodalDatalike.m -a CueBMS_UnimodalGaussianDatalike.m -a CueBMS_BimodalDatalike.m -a CueBMS_BimodalGaussianDatalike.m